name: CORE4 label enforcement
permissions:
  contents: read
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened, edited, ready_for_review]
jobs:
  require-label:
    uses: guardian/.github/.github/workflows/require-label.yaml@d8e99387686ec439e37c883ba9bb8ab2b43a6b81 #  v3.0.0
